proxies:
- name:  _CN_中国->SG_新加坡
  server:  x.gotout.work
  port:  30041
  type:  ss
  cipher:  aes-256-gcm
  password:  8SFY7w
  udp:  true
- name:  _US_美国
  server:  167.88.61.109
  port:  7307
  type:  ss
  cipher:  aes-256-gcm
  password:  FoOiGlkAA9yPEGP
  udp:  true
- name:  _US_美国  2
  server:  38.75.136.58
  port:  5004
  type:  ss
  cipher:  aes-256-gcm
  password:  g5MeD6Ft3CWlJId
  udp:  true
- name:  _US_美国  3
  server:  38.75.136.45
  port:  5004
  type:  ss
  cipher:  aes-256-gcm
  password:  g5MeD6Ft3CWlJId
  udp:  true
- name:  _US_美国  4
  server:  167.88.62.34
  port:  8080
  type:  ss
  cipher:  aes-256-gcm
  password:  KixLvKzwjekG00rm
  udp:  true
- name:  _US_美国  5
  server:  167.88.61.204
  port:  443
  type:  ss
  cipher:  aes-256-gcm
  password:  pKEW8JPByTVTLtM
  udp:  true
- name:  _US_美国  6
  server:  169.197.143.157
  port:  5003
  type:  ss
  cipher:  aes-256-gcm
  password:  g5MeD6Ft3CWlJId
  udp:  true
- name:  _US_美国  7
  server:  167.88.62.34
  port:  2375
  type:  ss
  cipher:  aes-256-gcm
  password:  faBAoD54k87UJG7
  udp:  true
- name:  _US_美国  8
  server:  38.143.66.71
  port:  5004
  type:  ss
  cipher:  aes-256-gcm
  password:  g5MeD6Ft3CWlJId
  udp:  true
- name:  _US_美国  9
  server:  38.68.134.202
  port:  2376
  type:  ss
  cipher:  aes-256-gcm
  password:  faBAoD54k87UJG7
  udp:  true
- name:  _US_美国  10
  server:  38.68.135.19
  port:  5004
  type:  ss
  cipher:  aes-256-gcm
  password:  g5MeD6Ft3CWlJId
  udp:  true
- name:  _GB_英国
  server:  212.38.189.174
  port:  6379
  type:  ss
  cipher:  aes-256-gcm
  password:  zDNVedRFPQexG9v
  udp:  true
- name:  _US_美国  11
  server:  169.197.143.157
  port:  8119
  type:  ss
  cipher:  aes-256-gcm
  password:  cdBIDV42DCwnfIN
  udp:  true
- name:  _US_美国  12
  server:  169.197.141.91
  port:  9101
  type:  ss
  cipher:  aes-256-gcm
  password:  e4FCWrgpkji3QY
  udp:  true
- name:  _US_美国  13
  server:  38.75.136.45
  port:  2376
  type:  ss
  cipher:  aes-256-gcm
  password:  faBAoD54k87UJG7
  udp:  true
- name:  _US_美国  14
  server:  38.68.134.202
  port:  8091
  type:  ss
  cipher:  aes-256-gcm
  password:  PCnnH6SQSnfoS27
  udp:  true
- name: 1.80|httpsgitiov9999 131
  server: 198.41.221.169
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /sakura/
    headers:
      Host: zero1.a-yu.xyz
- name: 1.80|httpsgitiov9999 266
  server: v2ray.ifuckgfw.ga
  port: 8443
  type: vmess
  uuid: 86b31db8-7514-11ec-a376-52ac0014346a
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /nBaG3RmV/
    headers:
      Host: v2ray.ifuckgfw.ga
- name: 1.79| 美国阿伟科技油管 24
  server: 104.24.223.86
  port: 2053
  type: vmess
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: false
  network: ws
  ws-path: /eisasqa
  ws-headers:
    Host: us.fovi.tk
